### ISSUE TITLE
pasteAsPlainText not working

### ISSUE THREAD

**Issue by Anarchtism** [Julow/Unexpected-Keyboard-layouts#4]
I'm using the MessagEase layout. Doesn't seem like "pasteAsPlainText" does anything.

**Comment by Julow** [comment]
`pasteAsPlainText` is not handled by many apps indeed. Perhaps the app can be changed to make `shift + paste = pasteAsPlainText` so that layouts authors don't feel the need to use this key.

Anyway, feel free to change the layout :)

**Comment by Anarchtism** [comment]
Oh, it's the app not handling it? Interesting. Ctrl + Shift + V works to paste as plain text, however... But I also see that undo/redo doesn't work in one app (Obsidian), though Ctrl + Z/Ctrl + Shift + Z does. Hmm... Okay, guess I'll follow [this issue](https://github.com/Julow/Unexpected-Keyboard/issues/568) on keyboard combinations.
